Repository ferdinh/defcon-z, pull requests merged in 2019-05, with the labels that each got.

#31 Add In-game Clock
  DEFCON Z/Assets/Scripts/Simulation/Clock.cs
  DEFCON Z/Assets/Scripts/Simulation/Clock.cs.meta
Labels: enhancement

#33 Resource Gathering
  DEFCON Z/Assets/Scenes/SimulationDevScene.unity
  DEFCON Z/Assets/Scenes/SimulationDevScene.unity.meta
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/GameManager.cs.meta
  DEFCON Z/Assets/Scripts/Simulation.meta
  DEFCON Z/Assets/Scripts/Simulation/Clock.cs
  DEFCON Z/Assets/Scripts/Simulation/Clock.cs.meta
  DEFCON Z/Assets/Scripts/Simulation/Modifier.cs
  DEFCON Z/Assets/Scripts/Simulation/Modifier.cs.meta
  DEFCON Z/Assets/Scripts/Simulation/ModifierType.cs
  DEFCON Z/Assets/Scripts/Simulation/ModifierType.cs.meta
  DEFCON Z/Assets/Scripts/Simulation/Resource.cs
  DEFCON Z/Assets/Scripts/Simulation/Resource.cs.meta
  DEFCON Z/Assets/Scripts/Units/Faction.cs
  DEFCON Z/Assets/Scripts/Units/Faction.cs.meta
  DEFCON Z/Assets/Scripts/Units/FactionType.cs
  DEFCON Z/Assets/Scripts/Units/FactionType.cs.meta
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs.meta
Labels: enhancement

#34 Add "Left Alt" as Alternate Camera Panning Control
  DEFCON Z/Assets/Scripts/Player/CameraController.cs
  DEFCON Z/ProjectSettings/InputManager.asset
Labels: enhancement

#36 Level for Faction
  DEFCON Z/Assets/Scripts/Simulation/Level.cs
  DEFCON Z/Assets/Scripts/Simulation/Level.cs.meta
  DEFCON Z/Assets/Scripts/Simulation/ModifierType.cs
  DEFCON Z/Assets/Scripts/Units/Faction.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/LevelTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/LevelTest.cs.meta
Labels: enhancement

#37 Change FactionOwner type to Faction
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/Units/Faction.cs
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
Labels: enhancement

#38 Implement Unit Initialisation Method
  DEFCON Z/Assets/Scripts/Units/Human.cs
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/Assets/Scripts/Units/Zombie.cs
Labels: enhancement

#39 Resource Initialization Fix
  DEFCON Z/Assets/Scripts/Units/Faction.cs
Labels: fix

#40 Implement Player Controlled Unit Check
  DEFCON Z/Assets/Scripts/Player/Player.cs
Labels: enhancement

#42 Unit Combat
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
  DEFCON Z/Assets/Scenes/SimulationDevScene.unity
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/Player/InputController.cs
  DEFCON Z/Assets/Scripts/Simulation/Combat.cs
  DEFCON Z/Assets/Scripts/Simulation/Combat.cs.meta
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/CombatTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/CombatTest.cs.meta
Labels: enhancement

#43 Reduce Number of Iteration for Gather Resource
  DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs
Labels: refactor, testing

#44 Implement Fluent Design to Resource
  DEFCON Z/Assets/Scripts/Simulation/Resource.cs
  DEFCON Z/Assets/Scripts/Units/Faction.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs
Labels: refactor

#45 Implemented Basic Unit Death Sound
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/Assets/Sounds.meta
  DEFCON Z/Assets/Sounds/Units.meta
  DEFCON Z/Assets/Sounds/Units/TestDeathSound.ogg
  DEFCON Z/Assets/Sounds/Units/TestDeathSound.ogg.meta
Labels: enhancement

#47 Unit Recruitment
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
  DEFCON Z/Assets/Scenes/SimulationDevScene.unity
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/Simulation/Resource.cs
  DEFCON Z/Assets/Scripts/Units/Faction.cs
  DEFCON Z/Assets/Scripts/Units/Human.cs
  DEFCON Z/Assets/Scripts/Units/HumanFaction.cs
  DEFCON Z/Assets/Scripts/Units/HumanFaction.cs.meta
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/Assets/Scripts/Units/UnitPrefabList.cs
  DEFCON Z/Assets/Scripts/Units/UnitPrefabList.cs.meta
  DEFCON Z/Assets/Scripts/Units/ZombieFaction.cs
  DEFCON Z/Assets/Scripts/Units/ZombieFaction.cs.meta
Labels: enhancement

#51 Implement Point Status Bar
  DEFCON Z/Assets/Materials/Gradients.meta
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Scripts/Menu.meta
  DEFCON Z/Assets/Scripts/Menu/UnitTestScript.meta
  DEFCON Z/Assets/Scripts/Player/InGameUI.cs
  DEFCON Z/Assets/Scripts/Player/SliderBar.cs
  DEFCON Z/Assets/Scripts/Player/SliderBar.cs.meta
Labels: enhancement

#52 Sprint 1 main menu feature
  DEFCON Z/Assets/InitTestScene636922265709865922.unity
  DEFCON Z/Assets/InitTestScene636922265709865922.unity.meta
  DEFCON Z/Assets/InitTestScene636922271289289351.unity
  DEFCON Z/Assets/InitTestScene636922271289289351.unity.meta
  DEFCON Z/Assets/Materials/MenuBackground.mat
  DEFCON Z/Assets/Materials/MenuBackground.mat.meta
  DEFCON Z/Assets/Scenes/Levels/Menu.meta
  DEFCON Z/Assets/Scenes/Levels/Menu/MainMenu.unity
  DEFCON Z/Assets/Scenes/Levels/Menu/MainMenu.unity.meta
  DEFCON Z/Assets/Scenes/MenuSampleScene.unity
  DEFCON Z/Assets/Scenes/MenuSampleScene.unity.meta
  DEFCON Z/Assets/Scripts/Menu/MainMenu.cs
  DEFCON Z/Assets/Scripts/Menu/MainMenu.cs.meta
  DEFCON Z/Assets/Scripts/Menu/Rotator.cs
  DEFCON Z/Assets/Scripts/Menu/Rotator.cs.meta
  DEFCON Z/Assets/Scripts/Menu/SettingsMenu.cs
  DEFCON Z/Assets/Scripts/Menu/SettingsMenu.cs.meta
  DEFCON Z/Packages/manifest.json
  DEFCON Z/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#54 Base Game Difficulty Option
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/Simulation/Difficulty.cs
  DEFCON Z/Assets/Scripts/Simulation/Difficulty.cs.meta
  DEFCON Z/Assets/Scripts/Units/Faction.cs
Labels: enhancement

#58 Use Constraint Model for Test
  DEFCON Z/Assets/Tests/PlayMode Tests/LevelTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs
Labels: refactor

#59 Fix 4 CodeFactor Style
  DEFCON Z/Assets/Scripts/Simulation/Clock.cs
Labels: refactor

#62 Fix Code Styling Issues
  DEFCON Z/Assets/Scripts/Player/CameraController.cs
  DEFCON Z/Assets/Scripts/Player/Player.cs
Labels: refactor

#68 Code Style Fix
  DEFCON Z/Assets/Scripts/Entity/IDestructible.cs
  DEFCON Z/Assets/Scripts/Simulation/Level.cs
  DEFCON Z/Assets/Scripts/Simulation/Modifier.cs
  DEFCON Z/Assets/Scripts/Simulation/ModifierType.cs
  DEFCON Z/Assets/Scripts/Units/Zombie.cs
Labels: refactor

#70 Remove commented code
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
Labels: refactor

#71 Add Jordans TDD Unit Tests
  DEFCON Z/Assets/Scripts/Player/Player.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/PropTests.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/PropTests.cs.meta
  DEFCON Z/Assets/Tests/PlayMode Tests/SelectionTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/SelectionTest.cs.meta
Labels: testing

#73 Add Neils TDD Unit Tests
  DEFCON Z/Assets/Tests/PlayMode Tests/MainMenuTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/MainMenuTest.cs.meta
Labels: testing

#76 Sprint2 unity editor upgrade
  DEFCON Z/Assets/Textures.meta
  DEFCON Z/Logs/Packages-Update.log
  DEFCON Z/Packages/manifest.json
  DEFCON Z/ProjectSettings/ProjectVersion.txt
  DEFCON Z/ProjectSettings/XRSettings.asset
  README.md
Labels: enhancement

#77 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: docs

#90 Add Test for Faction
  DEFCON Z/Assets/Scripts/Units/Faction.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/FactionTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/FactionTest.cs.meta
Labels: testing

#91 Update Main Menu Tests
  DEFCON Z/Assets/Tests/PlayMode Tests/MainMenuTest.cs
Labels: testing

#92 Add base test class
  DEFCON Z/Assets/Tests/PlayMode Tests/BaseTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/BaseTest.cs.meta
Labels: testing

#93 Gui Scaling Fix
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
Labels: fix

#98 Update Menu Test
  DEFCON Z/Assets/Tests/PlayMode Tests/MainMenuTest.cs
Labels: fix

#99 Pause Menu Initial Functionality
  DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
  DEFCON Z/Assets/Scripts/UI/PauseMenu.cs
  DEFCON Z/Assets/Scripts/UI/PauseMenu.cs.meta
Labels: enhancement

#100 Implemented New Font "Good Brush"
  DEFCON Z/Assets/Fonts.meta
  DEFCON Z/Assets/Fonts/Good Brush.ttf
  DEFCON Z/Assets/Fonts/Good Brush.ttf.meta
  DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
  DEFCON Z/Assets/Scenes/GUI/Menu/MainMenu.unity
Labels: enhancement

#101 In Game UI Simulation Clock Updating
  DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Scripts/GameLevel/GameLevel.cs
  DEFCON Z/Assets/Scripts/Player/Player.cs
  DEFCON Z/Assets/Scripts/UI/InGameUI.cs
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs.meta
Labels: enhancement, fix, refactor

#103 Bake Level Lighting
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city/LightingData.asset
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city/LightingData.asset.meta
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city/Lightmap-0_comp_dir.png
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city/Lightmap-0_comp_dir.png.meta
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city/Lightmap-0_comp_light.exr
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city/Lightmap-0_comp_light.exr.meta
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city/ReflectionProbe-0.exr
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city/ReflectionProbe-0.exr.meta
Labels: enhancement

#104 Enable Mergify
  .mergify.yml
Labels: enhancement

#105 Fix null when unit destroyed
  DEFCON Z/Assets/Scripts/Units/Faction.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/FactionTest.cs
Labels: fix, ready to merge, testing

#106 Assign Baked Lighting
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
Labels: enhancement, ready to merge

#107 Remove Singleton
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/Simulation/Clock.cs
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/ProjectSettings/TagManager.asset
Labels: ready to merge, refactor

#108 Capture-able Zones
  DEFCON Z/Assets/Materials/Zone.meta
  DEFCON Z/Assets/Materials/Zone/FriendlyZone.mat
  DEFCON Z/Assets/Materials/Zone/FriendlyZone.mat.meta
  DEFCON Z/Assets/Prefabs/Level/Captureable Zone.prefab
  DEFCON Z/Assets/Prefabs/Level/Captureable Zone.prefab.meta
  DEFCON Z/Assets/Prefabs/Level/ZoneManager.prefab
  DEFCON Z/Assets/Prefabs/Level/ZoneManager.prefab.meta
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Scripts/GameLevel/CustomZoneContainer.cs
  DEFCON Z/Assets/Scripts/GameLevel/CustomZoneContainer.cs.meta
  DEFCON Z/Assets/Scripts/GameLevel/Zone.cs
  DEFCON Z/Assets/Scripts/GameLevel/Zone.cs.meta
  DEFCON Z/Assets/Scripts/GameLevel/ZoneManager.cs
  DEFCON Z/Assets/Scripts/GameLevel/ZoneManager.cs.meta
  DEFCON Z/Assets/Scripts/Player/InputController.cs
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
  DEFCON Z/Assets/Scripts/UI/SliderBar.cs
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/ProjectSettings/InputManager.asset
Labels: enhancement, ready to merge

#110 Dead Units Fix
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/Units/Human.cs
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/Assets/Scripts/Units/Zombie.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/CombatTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/SelectionTest.cs
Labels: fix, ready to merge, refactor

#109 Refactor Unit Movement Script
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
  DEFCON Z/Assets/Scripts/Entity/Actions.meta
  DEFCON Z/Assets/Scripts/Entity/Actions/IMoveable.cs
  DEFCON Z/Assets/Scripts/Entity/Actions/IMoveable.cs.meta
  DEFCON Z/Assets/Scripts/Player/Player.cs
  DEFCON Z/Assets/Scripts/Units/Actions.meta
  DEFCON Z/Assets/Scripts/Units/Actions/UnitMoveScript.cs
  DEFCON Z/Assets/Scripts/Units/Actions/UnitMoveScript.cs.meta
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
Labels: ready to merge, refactor

#112 Edit Mergify Rules
  .mergify.yml
Labels: repo

#111 Create IsHostile Extension
  DEFCON Z/Assets/Scripts/Utility/UnitExtensions.cs
  DEFCON Z/Assets/Scripts/Utility/UnitExtensions.cs.meta
  DEFCON Z/Assets/Tests/PlayMode Tests/Unit.meta
  DEFCON Z/Assets/Tests/PlayMode Tests/Unit/UnitExtensionsTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/Unit/UnitExtensionsTest.cs.meta
Labels: enhancement, ready to merge, safe to delete branch

#113 Refactor Resource Class
  DEFCON Z/Assets/Scripts/GameLevel/Zone.cs
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/Simulation/Resource.cs
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
  DEFCON Z/Assets/Scripts/Units/Faction.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs
Labels: ready to merge, refactor, safe to delete branch

#115 Unit Selection Box Implementation
  DEFCON Z/Assets/Materials/Indicator.meta
  DEFCON Z/Assets/Materials/Indicator/Blue.mat
  DEFCON Z/Assets/Materials/Indicator/Blue.mat.meta
  DEFCON Z/Assets/Materials/Indicator/Red.mat
  DEFCON Z/Assets/Materials/Indicator/Red.mat.meta
  DEFCON Z/Assets/Models/Generic/Arrow.blend
  DEFCON Z/Assets/Models/Generic/Arrow.blend.meta
  DEFCON Z/Assets/Models/Generic/Arrow.blend1
  DEFCON Z/Assets/Models/Generic/Arrow.blend1.meta
  DEFCON Z/Assets/Models/Generic/Arrow.mtl
  DEFCON Z/Assets/Models/Generic/Arrow.mtl.meta
  DEFCON Z/Assets/Models/Generic/Arrow.obj
  DEFCON Z/Assets/Models/Generic/Arrow.obj.meta
  DEFCON Z/Assets/Prefabs/Level/Arrow.prefab
  DEFCON Z/Assets/Prefabs/Level/Arrow.prefab.meta
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Scripts/Entity/IDestructible.cs
  DEFCON Z/Assets/Scripts/GameLevel/ZoneManager.cs
  DEFCON Z/Assets/Scripts/Objects/ObjectBase.cs
  DEFCON Z/Assets/Scripts/Objects/Prop.cs
  DEFCON Z/Assets/Scripts/Player/InputController.cs
  DEFCON Z/Assets/Scripts/Player/ObjectSelection.cs
  DEFCON Z/Assets/Scripts/Player/ObjectSelection.cs.meta
  DEFCON Z/Assets/Scripts/Player/Player.cs
  DEFCON Z/Assets/Scripts/UI/InGameUI.cs
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
  DEFCON Z/Assets/Scripts/UI/SelectionUI.cs
  DEFCON Z/Assets/Scripts/UI/SelectionUI.cs.meta
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/Assets/Scripts/Utility/Bouncer.cs
  DEFCON Z/Assets/Scripts/Utility/Bouncer.cs.meta
  DEFCON Z/Assets/Tests/PlayMode Tests/SelectionTest.cs
Labels: enhancement, ready to merge

#117 Add Road Signs
  DEFCON Z/Assets/Models/RoadSet/RoadSign.blend
  DEFCON Z/Assets/Models/RoadSet/RoadSign.blend.meta
  DEFCON Z/Assets/Models/RoadSet/RoadSign.blend1
  DEFCON Z/Assets/Models/RoadSet/RoadSign.blend1.meta
  DEFCON Z/Assets/Models/RoadSet/RoadSign.mtl
  DEFCON Z/Assets/Models/RoadSet/RoadSign.mtl.meta
  DEFCON Z/Assets/Models/RoadSet/RoadSign.obj
  DEFCON Z/Assets/Models/RoadSet/RoadSign.obj.meta
  DEFCON Z/Assets/Prefabs/Objects/Road Set/RoadSign.prefab
  DEFCON Z/Assets/Prefabs/Objects/Road Set/RoadSign.prefab.meta
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
Labels: enhancement, ready to merge, safe to delete branch

#118 Game Music
  DEFCON Z/Assets/Scenes/GUI/Menu/MainMenu.unity
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Sounds/Music.meta
  DEFCON Z/Assets/Sounds/Music/CreditsLoop_Ove Melaa - Whoozer.mp3
  DEFCON Z/Assets/Sounds/Music/CreditsLoop_Ove Melaa - Whoozer.mp3.meta
  DEFCON Z/Assets/Sounds/Music/Ove Melaa - Theme Crystalized.mp3
  DEFCON Z/Assets/Sounds/Music/Ove Melaa - Theme Crystalized.mp3.meta
  DEFCON Z/Assets/Sounds/Music/Ove Melaa - Tube Ambient Loop.ogg
  DEFCON Z/Assets/Sounds/Music/Ove Melaa - Tube Ambient Loop.ogg.meta
Labels: enhancement, ready to merge

#119 Implement Credits Menu
  DEFCON Z/Assets/Scenes/GUI/Credits.txt
  DEFCON Z/Assets/Scenes/GUI/Credits.txt.meta
  DEFCON Z/Assets/Scenes/GUI/Menu/Credits.txt
  DEFCON Z/Assets/Scenes/GUI/Menu/Credits.txt.meta
  DEFCON Z/Assets/Scenes/GUI/Menu/Credits.unity
  DEFCON Z/Assets/Scenes/GUI/Menu/Credits.unity.meta
  DEFCON Z/Assets/Scenes/GUI/Menu/MainMenu.unity
  DEFCON Z/Assets/Scripts/UI/CreditsMenu.cs
  DEFCON Z/Assets/Scripts/UI/CreditsMenu.cs.meta
  DEFCON Z/Assets/Scripts/UI/MainMenu.cs
  DEFCON Z/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, ready to merge

#120 Update `Clock` Documentation
  DEFCON Z/Assets/Scripts/Simulation/Clock.cs
Labels: ready to merge, refactor, safe to delete branch

#121 Add Build Queue to Unit Recruitment
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
  DEFCON Z/Assets/Scripts/Simulation/UnitBuilder.meta
  DEFCON Z/Assets/Scripts/Simulation/UnitBuilder/BuildFinishEventArgs.cs
  DEFCON Z/Assets/Scripts/Simulation/UnitBuilder/BuildFinishEventArgs.cs.meta
  DEFCON Z/Assets/Scripts/Simulation/UnitBuilder/BuildProgressEventArgs.cs
  DEFCON Z/Assets/Scripts/Simulation/UnitBuilder/BuildProgressEventArgs.cs.meta
  DEFCON Z/Assets/Scripts/Simulation/UnitBuilder/UnitBuilder.cs
  DEFCON Z/Assets/Scripts/Simulation/UnitBuilder/UnitBuilder.cs.meta
  DEFCON Z/Assets/Scripts/Simulation/UnitBuilder/UnitOrder.cs
  DEFCON Z/Assets/Scripts/Simulation/UnitBuilder/UnitOrder.cs.meta
  DEFCON Z/Assets/Scripts/Units/Faction.cs
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
Labels: enhancement, ready to merge, safe to delete branch

#125 Level Status
  DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/UI/InGameUI.cs
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
  DEFCON Z/Assets/Scripts/Units/Faction.cs
Labels: enhancement, ready to merge, refactor

#124 Special Abilities
  DEFCON Z/Assets/Models/Vehicles.meta
  DEFCON Z/Assets/Models/Vehicles/SR-71.blend
  DEFCON Z/Assets/Models/Vehicles/SR-71.blend.meta
  DEFCON Z/Assets/Models/Vehicles/SR-71.blend1
  DEFCON Z/Assets/Models/Vehicles/SR-71.blend1.meta
  DEFCON Z/Assets/Models/Vehicles/SR-71.mtl
  DEFCON Z/Assets/Models/Vehicles/SR-71.mtl.meta
  DEFCON Z/Assets/Models/Vehicles/SR-71.obj
  DEFCON Z/Assets/Models/Vehicles/SR-71.obj.meta
  DEFCON Z/Assets/Models/Weapons.meta
  DEFCON Z/Assets/Models/Weapons/bomb.blend
  DEFCON Z/Assets/Models/Weapons/bomb.blend.meta
  DEFCON Z/Assets/Models/Weapons/bomb.blend1
  DEFCON Z/Assets/Models/Weapons/bomb.blend1.meta
  DEFCON Z/Assets/Models/Weapons/bomb.mtl
  DEFCON Z/Assets/Models/Weapons/bomb.mtl.meta
  DEFCON Z/Assets/Models/Weapons/bomb.obj
  DEFCON Z/Assets/Models/Weapons/bomb.obj.meta
  DEFCON Z/Assets/Prefabs/Abilities.meta
  DEFCON Z/Assets/Prefabs/Abilities/PrecisionBomb.prefab
  DEFCON Z/Assets/Prefabs/Abilities/PrecisionBomb.prefab.meta
  DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Scripts/Player/ObjectSelection.cs
  DEFCON Z/Assets/Scripts/Player/Player.cs
  DEFCON Z/Assets/Scripts/Player/SpecialAbilities.cs
  DEFCON Z/Assets/Scripts/Player/SpecialAbilities.cs.meta
  DEFCON Z/Assets/Scripts/UI/InGameUI.cs
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
  DEFCON Z/Assets/Scripts/UI/SpecialAbilitiesUI.cs
  DEFCON Z/Assets/Scripts/UI/SpecialAbilitiesUI.cs.meta
  DEFCON Z/Assets/Scripts/Units/Special.meta
  DEFCON Z/Assets/Scripts/Units/Special/BombCollider.cs
  DEFCON Z/Assets/Scripts/Units/Special/BombCollider.cs.meta
  DEFCON Z/Assets/Scripts/Units/Special/PrecisionBomb.cs
  DEFCON Z/Assets/Scripts/Units/Special/PrecisionBomb.cs.meta
  DEFCON Z/Assets/Scripts/Units/Special/SpecialAbility.cs
  DEFCON Z/Assets/Scripts/Units/Special/SpecialAbility.cs.meta
  DEFCON Z/Assets/Sounds/SFX.meta
  DEFCON Z/Assets/Sounds/SFX/explosion.ogg
  DEFCON Z/Assets/Sounds/SFX/explosion.ogg.meta
Labels: enhancement, ready to merge
