Repository ferdinh/defcon-z, pull requests merged in 2019-06, with the labels that each got.

#127 Enable Faction Level Up
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
  DEFCON Z/Assets/Scripts/Simulation/Combat.cs
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
Labels: enhancement, ready to merge, safe to delete branch

#128 Enable Force Recruit Unit
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
  DEFCON Z/Assets/Scripts/Units/Faction.cs
Labels: refactor, safe to delete branch

#129 Fix Recruit Unit Button
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
Labels: fix, safe to delete branch

#130 Fix Unit Extension Test
  DEFCON Z/Assets/Tests/PlayMode Tests/Unit/UnitExtensionsTest.cs
Labels: fix, safe to delete branch, testing

#131 Implement Basic AI
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
  DEFCON Z/Assets/Scripts/Entity/Actions/IMoveable.cs
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/Simulation/AI.cs
  DEFCON Z/Assets/Scripts/Simulation/AI.cs.meta
  DEFCON Z/Assets/Scripts/Units/Actions/UnitMoveScript.cs
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
Labels: enhancement, ready to merge, safe to delete branch

#123 LWRP Project Conversion
  DEFCON Z/Assets/LightweightRenderPipelineAsset.asset
  DEFCON Z/Assets/LightweightRenderPipelineAsset.asset.meta
  DEFCON Z/Assets/Materials/GrassMat.mat
  DEFCON Z/Assets/Materials/Indicator/Blue.mat
  DEFCON Z/Assets/Materials/Indicator/Red.mat
  DEFCON Z/Assets/Materials/MenuBackground.mat
  DEFCON Z/Assets/Materials/RED_ENEMY_DEBUG_MATERIAL.mat
  DEFCON Z/Assets/Materials/Zone/FriendlyZone.mat
  DEFCON Z/Assets/New Terrain.asset
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city/NavMesh.asset
  DEFCON Z/Assets/Shaders.meta
  DEFCON Z/Assets/Shaders/Fire.mat
  DEFCON Z/Assets/Shaders/Fire.mat.meta
  DEFCON Z/Assets/Shaders/Fire.shadergraph
  DEFCON Z/Assets/Shaders/Fire.shadergraph.meta
  DEFCON Z/Assets/Shaders/Water.mat
  DEFCON Z/Assets/Shaders/Water.mat.meta
  DEFCON Z/Assets/Shaders/Water.shadergraph
  DEFCON Z/Assets/Shaders/Water.shadergraph.meta
  DEFCON Z/Assets/Textures.meta
  DEFCON Z/Assets/Textures/fireAlpha.png
  DEFCON Z/Assets/Textures/fireAlpha.png.meta
  DEFCON Z/Assets/Textures/fireAlpha2.png
  DEFCON Z/Assets/Textures/fireAlpha2.png.meta
  DEFCON Z/Packages/manifest.json
  DEFCON Z/ProjectSettings/GraphicsSettings.asset
  DEFCON Z/ProjectSettings/ProjectSettings.asset
  DEFCON Z/ProjectSettings/QualitySettings.asset
  README.md
Labels: enhancement, help wanted, ready to merge, refactor

#133 Add Abundance Event
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/Simulation/Events.cs
  DEFCON Z/Assets/Scripts/Simulation/Events.cs.meta
Labels: enhancement, ready to merge, safe to delete branch

#132 Level Enhancements
  DEFCON Z/Assets/Materials/Zone/EnemyZone.mat
  DEFCON Z/Assets/Materials/Zone/EnemyZone.mat.meta
  DEFCON Z/Assets/Materials/Zone/NeutralZone.mat
  DEFCON Z/Assets/Materials/Zone/NeutralZone.mat.meta
  DEFCON Z/Assets/Models/Buildings/GasStation.blend
  DEFCON Z/Assets/Models/Buildings/GasStation.blend.meta
  DEFCON Z/Assets/Models/Buildings/GasStation.blend1
  DEFCON Z/Assets/Models/Buildings/GasStation.blend1.meta
  DEFCON Z/Assets/Models/Buildings/GasStation.mtl
  DEFCON Z/Assets/Models/Buildings/GasStation.mtl.meta
  DEFCON Z/Assets/Models/Buildings/GasStation.obj
  DEFCON Z/Assets/Models/Buildings/GasStation.obj.meta
  DEFCON Z/Assets/Models/Buildings/House10m.blend
  DEFCON Z/Assets/Models/Buildings/House10m.blend.meta
  DEFCON Z/Assets/Models/Buildings/House10m.blend1
  DEFCON Z/Assets/Models/Buildings/House10m.blend1.meta
  DEFCON Z/Assets/Models/Buildings/House10m.mtl
  DEFCON Z/Assets/Models/Buildings/House10m.mtl.meta
  DEFCON Z/Assets/Models/Buildings/House10m.obj
  DEFCON Z/Assets/Models/Buildings/House10m.obj.meta
  DEFCON Z/Assets/Models/Buildings/bridge.blend
  DEFCON Z/Assets/Models/Buildings/bridge.blend.meta
  DEFCON Z/Assets/Models/Buildings/bridge.blend1
  DEFCON Z/Assets/Models/Buildings/bridge.blend1.meta
  DEFCON Z/Assets/Models/Buildings/bridge.mtl
  DEFCON Z/Assets/Models/Buildings/bridge.mtl.meta
  DEFCON Z/Assets/Models/Buildings/bridge.obj
  DEFCON Z/Assets/Models/Buildings/bridge.obj.meta
  DEFCON Z/Assets/New Terrain.asset
  DEFCON Z/Assets/Prefabs/Level/Captureable Zone.prefab
  DEFCON Z/Assets/Prefabs/Objects/Buildings/House10m.prefab
  DEFCON Z/Assets/Prefabs/Objects/Buildings/House10m.prefab.meta
  DEFCON Z/Assets/Prefabs/Props/TreePaint.prefab
  DEFCON Z/Assets/Prefabs/Props/TreePaint.prefab.meta
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city/NavMesh.asset
  DEFCON Z/Assets/Scripts/GameLevel/CustomZoneContainer.cs
  DEFCON Z/Assets/Scripts/GameLevel/Zone.cs
  DEFCON Z/Assets/Scripts/GameLevel/ZoneManager.cs
  DEFCON Z/Assets/Shaders/Water.mat
Labels: enhancement, ready to merge

#135 Perks Additions
  DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Scripts/Player/Perks.cs
  DEFCON Z/Assets/Scripts/Player/Perks.cs.meta
  DEFCON Z/Assets/Scripts/Player/Player.cs
  DEFCON Z/Assets/Scripts/Simulation/ModifierType.cs
  DEFCON Z/Assets/Scripts/Simulation/Resource.cs
  DEFCON Z/Assets/Scripts/UI/PerksUI.cs
  DEFCON Z/Assets/Scripts/UI/PerksUI.cs.meta
  DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
Labels: enhancement, ready to merge, safe to delete branch

#134 Game Sound
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Scripts/Player/GameSound.cs
  DEFCON Z/Assets/Scripts/Player/GameSound.cs.meta
  DEFCON Z/Assets/Scripts/Simulation/Combat.cs
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/Assets/Sounds/Units/HumanAttack.ogg
  DEFCON Z/Assets/Sounds/Units/HumanAttack.ogg.meta
  DEFCON Z/Assets/Sounds/Units/TestDeathSound.ogg
Labels: enhancement, ready to merge, safe to delete branch

#136 Update Max Point Test
  DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs
Labels: ready to merge, safe to delete branch, testing

#137 Add Null Check for Combat Audio
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
Labels: ready to merge, safe to delete branch, testing

#139 Victory Screen Unit Test
  DEFCON Z/Assets/Tests/PlayMode Tests/VictoryScreenTest.cs
  DEFCON Z/Assets/Tests/PlayMode Tests/VictoryScreenTest.cs.meta
Labels: ready to merge, safe to delete branch, testing

#140 Sprint 2 Polish
  DEFCON Z/Assets/Prefabs/Units/Human.prefab
  DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
  DEFCON Z/Assets/Scenes/GUI/Credits.txt
  DEFCON Z/Assets/Scenes/GUI/Credits.txt.meta
  DEFCON Z/Assets/Scenes/GUI/IGUI Test.unity
  DEFCON Z/Assets/Scenes/GUI/IGUI Test.unity.meta
  DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
  DEFCON Z/Assets/Scenes/GUI/Menu/Credits.txt
  DEFCON Z/Assets/Scenes/GUI/Menu/Credits.unity
  DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
  DEFCON Z/Assets/Scripts/GameManager.cs
  DEFCON Z/Assets/Scripts/Player/Player.cs
  DEFCON Z/Assets/Scripts/Simulation/AI.cs
  DEFCON Z/Assets/Scripts/UI/MainMenu.cs
  DEFCON Z/Assets/Scripts/UI/PauseMenu.cs
  DEFCON Z/Assets/Scripts/UI/PerksUI.cs
  DEFCON Z/Assets/Scripts/UI/SpecialAbilitiesUI.cs
  DEFCON Z/Assets/Scripts/Units/Actions/UnitAttackScript.cs
  DEFCON Z/Assets/Scripts/Units/Actions/UnitMoveScript.cs
  DEFCON Z/Assets/Scripts/Units/Special/PrecisionBomb.cs
  DEFCON Z/Assets/Scripts/Units/Special/SpecialAbility.cs
  DEFCON Z/ProjectSettings/EditorBuildSettings.asset
  DEFCON Z/ProjectSettings/GraphicsSettings.asset
Labels: enhancement
