Repository ferdinh/defcon-z, pull requests merged in 2019-04, with the labels that each got.

#8 Test Setup for Unity3D
  DEFCON Z/Assets/Tests.meta
  DEFCON Z/Assets/Tests/EditMode Tests.meta
  DEFCON Z/Assets/Tests/EditMode Tests/EditMode Tests.asmdef
  DEFCON Z/Assets/Tests/EditMode Tests/EditMode Tests.asmdef.meta
  DEFCON Z/Assets/Tests/PlayMode Tests.meta
  DEFCON Z/Assets/Tests/PlayMode Tests/PlayMode Tests.asmdef
  DEFCON Z/Assets/Tests/PlayMode Tests/PlayMode Tests.asmdef.meta
Labels: testing

#9 Fix panning affecting height bug
  DEFCON Z/Assets/Scripts/Player/CameraController.cs
Labels: fix

#10 Add Build Settings
  DEFCON Z/ProjectSettings/GraphicsSettings.asset
  DEFCON Z/ProjectSettings/ProjectSettings.asset
  DEFCON Z/ProjectSettings/UnityConnectSettings.asset
Labels: enhancement

#13 Base Object/Unit Implementation
  DEFCON Z/Assets/Materials.meta
  DEFCON Z/Assets/Materials/GrassMat.mat
  DEFCON Z/Assets/Materials/GrassMat.mat.meta
  DEFCON Z/Assets/Models.meta
  DEFCON Z/Assets/Models/Barrel.blend
  DEFCON Z/Assets/Models/Barrel.blend.meta
  DEFCON Z/Assets/Models/Barrel.blend1
  DEFCON Z/Assets/Models/Barrel.blend1.meta
  DEFCON Z/Assets/Models/Barrel.mtl
  DEFCON Z/Assets/Models/Barrel.mtl.meta
  DEFCON Z/Assets/Models/Barrel.obj
  DEFCON Z/Assets/Models/Barrel.obj.meta
  DEFCON Z/Assets/Models/Tree1.blend
  DEFCON Z/Assets/Models/Tree1.blend.meta
  DEFCON Z/Assets/Models/Tree1.blend1
  DEFCON Z/Assets/Models/Tree1.blend1.meta
  DEFCON Z/Assets/Models/Tree1.mtl
  DEFCON Z/Assets/Models/Tree1.mtl.meta
  DEFCON Z/Assets/Models/Tree1.obj
  DEFCON Z/Assets/Models/Tree1.obj.meta
  DEFCON Z/Assets/Prefabs/Barrel Prop.prefab
  DEFCON Z/Assets/Prefabs/Barrel Prop.prefab.meta
  DEFCON Z/Assets/Prefabs/Player.prefab
  DEFCON Z/Assets/Scenes/GameObjectTestsScene.unity
  DEFCON Z/Assets/Scenes/GameObjectTestsScene.unity.meta
  DEFCON Z/Assets/Scenes/ObjectSelectionScene.meta
  DEFCON Z/Assets/Scenes/ObjectSelectionScene.unity
  DEFCON Z/Assets/Scenes/ObjectSelectionScene.unity.meta
  DEFCON Z/Assets/Scenes/ObjectSelectionScene/NavMesh.asset
  DEFCON Z/Assets/Scenes/ObjectSelectionScene/NavMesh.asset.meta
  DEFCON Z/Assets/Scripts/Objects.meta
  DEFCON Z/Assets/Scripts/Objects/ObjectBase.cs
  DEFCON Z/Assets/Scripts/Objects/ObjectBase.cs.meta
  DEFCON Z/Assets/Scripts/Objects/Prop.cs
  DEFCON Z/Assets/Scripts/Objects/Prop.cs.meta
  DEFCON Z/Assets/Scripts/Player/CameraController.cs
  DEFCON Z/Assets/Scripts/Player/InputController.cs
  DEFCON Z/Assets/Scripts/Player/InputController.cs.meta
  DEFCON Z/Assets/Scripts/Player/Player.cs
  DEFCON Z/Assets/Scripts/Player/Player.cs.meta
  DEFCON Z/Assets/Scripts/Units.meta
  DEFCON Z/Assets/Scripts/Units/Human.cs
  DEFCON Z/Assets/Scripts/Units/Human.cs.meta
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs
  DEFCON Z/Assets/Scripts/Units/UnitBase.cs.meta
  DEFCON Z/ProjectSettings/EditorBuildSettings.asset
  DEFCON Z/ProjectSettings/TagManager.asset
Labels: enhancement
